version: "3"

services:
  # faredm:
  #   restart: unless-stopped
  #   build:
  #     context: ./fe
  #     dockerfile: Dockerfile
  #   environment:
  #     - ENV
  #     - JWT
  #     - CERTKEY
  #     - CERTCHAIN
  #   volumes:
  #     - /etc/letsencrypt:/etc/nginx/certs/
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - db
  #     - api
  # api:
  #   restart: unless-stopped
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   environment:
  #     - ENV
  #     - JWT
  #     - CERTKEY
  #     - CERTCHAIN
  #   network_mode: "host"
  #   command: ["node", "index.js"]
  #   volumes:
  #     - /etc/letsencrypt/live/weskool.team:/etc/letsencrypt/live/weskool.team/
  #     - /etc/letsencrypt/archive/weskool.team:/etc/letsencrypt/archive/weskool.team/
  #   depends_on:
  #     - db


  # Mongo DB server
  mongodb:
    container_name: mongo-dm
    restart: unless-stopped
    image: mongo
    network_mode: "host"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ~/projs/digitalmatatus/db/nodes/rdb1:/data/db

  # Mariadb server
  sqldb:
    container_name: mariadb-dm
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    networks: 
      - sql

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=sqldb
      - MYSQL_ROOT_PASSWORD
    ports:
      - "8081:80"
    depends_on:
      - sqldb
    networks:
      - sql

networks:
  sql:
